before_install:
  - gem update --system 2.1.11
  - gem --version
rvm:
  - ree
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.3
gemfile:
  - Gemfile
matrix:
  include:
    - rvm: jruby-19mode
      gemfile: Gemfile.jruby
  allow_failures:
    - rvm: jruby-19mode
